on:
  push:
    branches:
      - main

name: Build Neral Mobile (Android) App

jobs:
  build:
    name: Build and Release new APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          # artifacts: "build/app/outputs/apk/release/*"
          artifacts: "build/app/outputs/flutter-apk/*"
          tag: ${{ github.ref_name }}
          token: ${{ secrets.TOKEN }}
